### ISSUE TITLE
Unable to Satisfy Dependencies with Python 3 or 2.7 on Ubuntu 22.04

### ISSUE THREAD

**Issue by W4JEW** [k4yt3x/sds-submaker#1]
Hello!

I tried installing your app on a computer running Ubuntu 22.04. I have both python3 and python2.7 installed... I tried python3 first, then python2.7. I seem to run into the same issues regardless.

```
ubuntu:~/git/sds-submaker$ pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/user/git/sds-submaker
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-20cn5klv/overlay/local/lib/python3.10/dist-packages/pdm/pep517/api.py", line 26, in get_requires_for_build_wheel
          if builder.meta.config.run_setuptools:
        File "/tmp/pip-build-env-20cn5klv/overlay/local/lib/python3.10/dist-packages/pdm/pep517/base.py", line 154, in meta
          self._meta.validate(True)
        File "/tmp/pip-build-env-20cn5klv/overlay/local/lib/python3.10/dist-packages/pdm/pep517/metadata.py", line 58, in validate
          return validate_pep621(self.data, raising)
        File "/tmp/pip-build-env-20cn5klv/overlay/local/lib/python3.10/dist-packages/pdm/pep517/validator.py", line 85, in validate_pep621
          raise PEP621ValidationError(validator.errors)
      pdm.pep517.exceptions.PEP621ValidationError: {'license-expression': ['unknown field']}
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

So I tried manually installing pep517:

```
pip install pdm-pep517
```

```
user@ubuntu:~$ pip install pep517
Defaulting to user installation because normal site-packages is not writeable
Collecting pep517
  Downloading pep517-0.13.0-py3-none-any.whl (18 kB)
Collecting tomli>=1.1.0
  Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
Installing collected packages: tomli, pep517
Successfully installed pep517-0.13.0 tomli-2.0.1
```

Then tried the install routine for sds-submaker again:

```
user@ubuntu:~$ cd git/sds-submaker/
user@ubuntu:~/git/sds-submaker$ pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/user/git/sds-submaker
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-xke52wss/overlay/local/lib/python3.10/dist-packages/pdm/pep517/api.py", line 26, in get_requires_for_build_wheel
          if builder.meta.config.run_setuptools:
        File "/tmp/pip-build-env-xke52wss/overlay/local/lib/python3.10/dist-packages/pdm/pep517/base.py", line 154, in meta
          self._meta.validate(True)
        File "/tmp/pip-build-env-xke52wss/overlay/local/lib/python3.10/dist-packages/pdm/pep517/metadata.py", line 58, in validate
          return validate_pep621(self.data, raising)
        File "/tmp/pip-build-env-xke52wss/overlay/local/lib/python3.10/dist-packages/pdm/pep517/validator.py", line 85, in validate_pep621
          raise PEP621ValidationError(validator.errors)
      pdm.pep517.exceptions.PEP621ValidationError: {'license-expression': ['unknown field']}
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

According to [pypi.org docs for pep517](https://pypi.org/project/pdm-pep517/), the pep517 package is 

_This is the backend for PDM projects, while you can also use it alone. It reads the metadata of PEP 621 format and coverts it to Core metadata._

So, I'm at a loss for what to do to resolve the dependencies for sds-submaker. Any advice?

**Comment by k4yt3x** [comment]
PDM, for whatever reason, has decided to deprecate the `license-expression` without providing warning or backwards compatibility. When they pushed that out a whole bunch of my repos broke. I just fixed it. It should work now.
